<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container8gGkSsT\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8gGkSsT/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container8gGkSsT.legacy');
=======
if (\class_exists(\ContainerYnkPrXL\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYnkPrXL/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYnkPrXL.legacy');
>>>>>>> 1030b1a5cf19101fc673f98e6c6ac1410d6cea73

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container8gGkSsT\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container8gGkSsT\appAppKernelProdContainer([
    'container.build_hash' => '8gGkSsT',
    'container.build_id' => '423afcae',
    'container.build_time' => 1722299295,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8gGkSsT');
=======
    \class_alias(\ContainerYnkPrXL\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYnkPrXL\appAppKernelProdContainer([
    'container.build_hash' => 'YnkPrXL',
    'container.build_id' => 'fb267c79',
    'container.build_time' => 1722294789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYnkPrXL');
>>>>>>> 1030b1a5cf19101fc673f98e6c6ac1410d6cea73
