<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYnkPrXL\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYnkPrXL/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYnkPrXL.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYnkPrXL\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerYnkPrXL\appAppKernelProdContainer([
    'container.build_hash' => 'YnkPrXL',
    'container.build_id' => 'fb267c79',
    'container.build_time' => 1722294789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYnkPrXL');
